# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/


stages:
  - test
  - publish
cache:
  paths:
  - node_modules/

test_with_lab:
  image: node:8.12
  stage: test
  script:
    - cd NaturalSearch && npm install
    - npm run test

  artifacts:
    paths:
      - node_modules/

.publish_docker_hub:
  image: docker
  services:
    - docker:dind
  script:
    - docker login -p $DOCKERPASSWORD -u $DOCKERLOGIN
    - docker build . -t zero101010/NSvis:$VERSION
    - docker push zero101010/NSvis:$VERSION
  tags:
    - docker

publish_master:
  extends: .publish_docker_hub
  environment: master
  only: 
    - master

publish_development:
  extends: .publish_docker_hub
  environment: development
  only: 
    - development

deploy:
  script:
    - apt-get -y update
    - apt-get -y install sshpass
    - ./deploy.sh $IP $PASSWORD
  