# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/


stages:
  - test
  - publish
  - deploy
cache:
  paths:
  - node_modules/

test_with_lab:
  image: node:8.12
  stage: test
  script:
    - cd NaturalSearch && npm install
    - npm run test

  artifacts:
    paths:
      - node_modules/

.publish_docker_hub:
  image: docker
  stage: publish
  services:
    - docker:dind
  script:
    - docker login -p $DOCKERPASSWORD -u $DOCKERLOGIN
    - cd NaturalSearch
    - docker build . -t zero101010/nsvis:latest
    - docker push zero101010/nsvis:latest
  tags:
    - docker

publish_master:
  extends: .publish_docker_hub
  environment: master
  only: 
    - master

deploy:
  stage: deploy
  script:
    - apt-get update 
    - apt-get -y install sshpass
    - ls
    - ./deploy.sh $PASSWORD $IP 
    - apt-get -y update
  only:
    - master
  